<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <SignAssembly>false</SignAssembly>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Countly.UI.WebView2\Countly.UI.WebView2.csproj" />
    <ProjectReference Include="..\..\netstd\Countly\Countly.csproj" />
  </ItemGroup>
</Project>
